name: nuget

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  nuget-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Together.slnx

      - name: Build
        run: dotnet build Together.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Together.slnx --configuration Release --no-build

      - name: Pack
        run: dotnet pack Together.slnx --configuration Release --no-build -p:IncludeSymbols=false -p:SymbolPackageFormat=snupkg -o "packages"

      - name: Push
        run: dotnet nuget push "packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
